### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by owtotwo** [jskyzero/Git#1]
我看看

**Comment by owtotwo** [comment]
1. 我写好了结构给你就不要自己随便改main函数了好吧……我不是写清楚了/* Your code here */吗？没看到？
2. makefile是什么鬼为什么不能用，写的是什么？编译头文件干嘛？
4. 都说了谷歌风格了缩进还用之前的大括号换行？你喜欢这种风格也行，但我要求是谷歌风格，就要按我要求做，你平常什么风格我不管，这里请按要求。
5. "int hex_viewer(char *str)"里的命名str应该明确为file_address之类的，谁知道你str是干嘛的
6. 你确定在Windows下不会出错？你试试看？测一下带回车的文本文件。
8. 出了while就肯定eof的了你还判断ferror干毛线？
7. num这个很难看出是指位置啊，要不就换命名要不就注释。
9. 注释了的东西没意义的为什么不删掉？
10. 为什么主要业务逻辑部分不写注释？（我不写我又不是给别人看的我是测task可行性，你写是给人看的你不写注释别人很难做的）
11. line 50里的"if (0 == c[i] || -1 == c[i])"的-1是什么鬼，鬼知道你什么意思，如果是EOF为啥上面又用EOF下面不用，如果不是那代表什么意思？常量就给它个名字啊。
13. main.c函数里的puts你知不知道是自动加个换行的？后面还\n?
14. 你有没有编译过才给我的？有3个warning不看？iscntrl()函数的头文件呢？类型转换呢？
![image](https://cloud.githubusercontent.com/assets/13444035/18538398/3d764126-7b40-11e6-8cd9-5f5df139e704.png)
15. 直接测试都没过难道是我找错你的文件了……？
16. 我看不下去了。

**Comment by jskyzero** [comment]
1,已按照标准格式
２，makefile忘记跟新了抱歉
３，已改正
４，已修改
５，是我测试出了问题
６，已删除
７，已修改
８，已删除
９，已添加注释
１０，已修改
１１，已修改
１２，以增加
１３，希望再次测试
１４，抱歉添麻烦了，下次会尽量做的更好

**Comment by jskyzero** [comment]
1,已按照标准格式
２，makefile忘记跟新了抱歉
３，已改正
４，已修改
５，是我测试出了问题
６，已删除
７，已修改
８，已删除
９，已添加注释
１０，已修改
１１，已修改
１２，以增加
１３，希望再次测试
１４，抱歉添麻烦了，下次会尽量做的更好
